# Generated by Django 2.2.14 on 2020-07-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('TO', 'Toys'), ('EL', 'Electronics'), ('HO', 'Home'), ('FA', 'Fashion'), ('OT', 'Other')], default='OT', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
