# Generated by Django 2.2.14 on 2020-07-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200714_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='desctiption',
            new_name='description',
        ),
    ]
