# Generated by Django 2.2.14 on 2020-07-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200715_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='user_id',
            new_name='user',
        ),
    ]
