# Generated by Django 2.2.14 on 2020-07-17 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionimage',
            name='user',
            field=models.ForeignKey(default='auctions.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
