# Generated by Django 2.2.14 on 2020-07-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200717_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionimage',
            name='user',
        ),
    ]
