# Generated by Django 2.2.14 on 2020-07-28 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200717_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionimage',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction'),
        ),
    ]
