# Generated by Django 2.2.14 on 2020-07-30 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auction_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AddField(
            model_name='comment',
            name='auction_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction'),
            preserve_default=False,
        ),
    ]
