# Generated by Django 2.2.14 on 2020-07-31 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200730_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TO', 'Toys'), ('EL', 'Electronics'), ('HO', 'Home'), ('FA', 'Fashion'), ('OT', 'Other')], default='OT', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(default='OT', on_delete=django.db.models.deletion.SET_DEFAULT, to='auctions.Category'),
        ),
    ]
